### PR TITLE
ReadMe cleanup

### PR DESCRIPTION
**Pull request by BrokenCommander**
Please review and then translate the spanish version :smiley:

### CODE REVIEW

**Comment by bite-your-idols** [comment]
nice!!
only strange lines I see are these ones:

> Use SSH to connect to your Raspberry Pi (PuTTY for Windows, Terminus for mobile)
Download the latest release with wget

I preffer only mentioning manual download because many noob users come here and with those lines it seems that you need to use bash programming skills (ssh/wget...) in order to make it run. Advanced users already know they can download a zip zile from github using ssh.

I think it would be better just one line:

> -  Download the latest addon zip release. 

or something similar XD

good work!

**Comment by BrokenCommander** [comment]
I was actually trying to help the noobs by giving them small instructions on how to get the zip, I even linked to the [LibreELEC manual](https://wiki.libreelec.tv/index.php?title=Accessing_LibreELEC#tab=SSH) which describes how to enable SSH and connect to it.
Should I go more in depth (how to get IP, how to use `wget`) or should I just write *Download the lastest release*?

Anyway we could also host a repo on GitHub or my webserver if that would make it easier.

**Comment by bite-your-idols** [comment]
Yes, I think " Download the lastest release" is enough.
About repo, I was thinking about it some months ago and finally I let it go... It will be easier for users to update and get notifications when updates release but I didn't want to study how to create it... 

Also, I am about to release v2.7 so I will make a couple edits in readme file. what do you prefer I can edit your version or I can edit mine and then you modify yours?

**Comment by BrokenCommander** [comment]
Well, I'm going to edit the ReadMe now - simplify the instructions and add you to the credits. I can also edit the spanish version so you only have to translate a few more things (less work for you).
You can then merge it and make your changes for the 2.7 release. I will then translate it for the german version and everything should be fine.

Should we create a english-only `CHANGELOG.MD`, write it into the `README.MD` or should we just stick with the `script.gamestarter/changelog.txt`?

About the repo, I can help you with that, but I've to read some docs because I never worked on something like this :see_no_evil:

**Comment by bite-your-idols** [comment]
done! tomorrow I will edit readme file.
About changelog, with addon changelog.txt and releases page info I think it is enough.
About repo, another possibility I consider is to include addon in an existing repo.

**Comment by BrokenCommander** [comment]
Sorry for the late response, I'll look into the new files as soon as I have some time.

Have you considered to introduce your project to [Kodinerds](https://www.kodinerds.net/)? I think their repo is a default one in LibreELEC and they have a subrepo for Raspberry Pi 2 stuff.

**Comment by bite-your-idols** [comment]
I think I finished editing readme files, so when you want (or can) you can edit the german one, there's no hurry.

About repo, I will take note, that can be one of the posible repos.

**Pull request merged**
